language: csharp

env:
  global:
    - CONFIGURATION="Release"
mono:
  - 3.12.0
  - 3.10.0
solution: FsMachines.sln

install:
  - sudo apt-get install nunit-console

script:
  - xbuild ./FsMachines.sln /p:Configuration=${CONFIGURATION}
  - nunit-console ./FsMachines.Tests/bin/${CONFIGURATION}/FsMachines.Tests.dll

